# Generated by Django 4.1.5 on 2023-01-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_drone_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='last_seen',
            field=models.CharField(max_length=20),
        ),
    ]
