# Generated by Django 4.1.5 on 2023-01-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_drone_options_alter_drone_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droneflightdatapoint',
            name='flight',
        ),
        migrations.DeleteModel(
            name='DroneFlight',
        ),
        migrations.DeleteModel(
            name='DroneFlightDataPoint',
        ),
    ]
